# Generated by Django 4.2.4 on 2023-11-14 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_friend_profile_delete_room_friend_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='friends',
        ),
        migrations.DeleteModel(
            name='Friend',
        ),
    ]
