# Generated by Django 4.2.4 on 2023-11-16 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_rename_msd_receiver_chatmessage_msg_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmessage',
            name='product_type',
            field=models.CharField(default='', max_length=255),
        ),
    ]
