# Generated by Django 4.2.4 on 2023-08-19 09:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_book_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='base.category', null=True),
        ),
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
