# Generated by Django 4.2.4 on 2023-09-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_materialcategory_rename_category_bookcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='category_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
