# Generated by Django 4.2.4 on 2023-09-09 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_rename_category_name_material_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='age_group',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
