# Generated by Django 4.2.4 on 2023-09-09 10:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_material_age_group_alter_material_company_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='material',
            name='donated_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='material',
            name='company',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
